### ISSUE TITLE
same product with different attribute in cart possible?

### ISSUE THREAD

**Issue by sigistardust** [wagnerwagner/merx#18] opened 2020-09-05 10:24 UTC
hello,

is it possible to add the same product to the cart twice, but with different attributes, e.g. a jacket in size 48 and a jacket in size 50. 
right now, the size of the first product just gets overwritten if i add the second product. 

i am trying to avoid the necessity of subpages for all product variations and would rather like to use a structure field in the product blueprint since it makes it much more easier to update, especially for a large amount of products.

any help on this is appreciated! 

thank you for the great work on this plugin!

**Comment by alexpi** [comment] 2020-10-01 20:14
Hello @sigistardust. Did you find a solution to your problem? I am in the exact same situation.

**Comment by sigistardust** [comment] 2020-10-02 10:35
hi @alexpi 
i actually found that splitting the variants up in different products is the better solution for me.
but still, this question is very interesting to me, especially for future projects.

**Comment by tobiasfabian** [comment] 2020-10-12 09:00
It would be possible to compare every attribute of a product and only merge products when every single attribute (except `quantity`) is the same. This would require some modifications of the [$productList->updateItem()](https://github.com/wagnerwagner/merx/blob/master/src/productList.php#L66) method. 

The following code would result in two ProductList/Cart entries and won’t be merged.

```php
$cart->add([
  'id' => 'jacket',
  'size' => 48,
]);
$cart->add([
  'id' => 'jacket',
  'size' => 50,
]);
```

What do you think?

**Comment by alexpi** [comment] 2020-10-12 10:49
So, if I get this right, this modification would allow products with the same id to be added to the cart, and abollish the necessity for subpage variations?

**Comment by tobiasfabian** [comment] 2020-10-12 10:55
Yes, that’s correct.

**Comment by alexpi** [comment] 2020-10-21 07:24
So, should I try to modify your code to enable this functionality or are you considering adding it to the plugin?

**Comment by tobiasfabian** [comment] 2020-10-22 16:16
@alexpi Today, I tried a different approach.

With the latest commit in the develop branch I modified the `Cart::add()` method. The `Cart::add` method now can handle one or two arguments.

You can provide a unique key as first argument and your cart item as the second argument. As long as the `key` is unique the items won’t be merged. So, the following would be possible.

```php
$cart->add('jacket-48', [
  'id' => 'jacket',
  'size' => 48,
]);
$cart->add('jacket-50', [
  'id' => 'jacket',
  'size' => 50,
]);
```

**Comment by sigistardust** [comment] 2020-10-26 18:18
@tobiasfabian @alexpi glad to see that you are looking for possible improvements on that! shall I leave the issue open?

**Comment by alexpi** [comment] 2020-10-26 18:26
@sigistardust I haven't tried the solution yet (I will in a few days), but it seems like it will solve my use case perfectly.

**Comment by tobiasfabian** [comment] 2020-10-27 08:30
> @tobiasfabian @alexpi glad to see that you are looking for possible improvements on that! shall I leave the issue open?

Yes, I’ll close it as soon as I think the issue is solved.

> @sigistardust I haven't tried the solution yet (I will in a few days), but it seems like it will solve my use case perfectly.

Looking forward to your feedback.

**Comment by sigistardust** [comment] 2020-10-28 10:30
@tobiasfabian I tried your last solution and adding to cart works for me! i will come back after testing more with the cart update and remove.

**Comment by sigistardust** [comment] 2020-10-28 10:53
@tobiasfabian could you please tell me what the easiest way is to: 
- filter the cart for a certain variation
- update the quantity of that variation
?

thank you very much!

**Comment by sigistardust** [comment] 2020-10-28 11:07
@tobiasfabian found a solution for me with the `add` method. looks like this inside my `config.php`:

```
'routes' => [
        [
          'method' => 'post',
          'pattern' => 'shop-api/add-to-cart',
          'action' => function() {
            try {
              $data = kirby()->request()->data();
              if (size(merx()->cart()->find($data['id'] . $data['size'])) > 0) {
                merx()->cart()->add($data['id'] . $data['size'], [
                  'id' => $data['id'],
                  'quantity' => merx()->cart()->find($data['id'] . $data['size'])['quantity'] + $data['quantity'],
                  'size' => $data['size'],
                ]);
              } else {
                merx()->cart()->add($data['id'] . $data['size'], [
                    'id' => $data['id'],
                    'quantity' => $data['quantity'],
                    'size' => $data['size'],
                ]);
              }
              go(page($data['id'])->url() . '/addedtoorder:yes');
            } catch (Kirby\Exception\Exception $ex) {
              return $ex->toArray();
            }
          },
        ],
    ]
```

**Comment by alexpi** [comment] 2020-11-14 09:48
@tobiasfabian I finally got to try this. It works great! I can't find how to update a variation on the cart though.

**Comment by tobiasfabian** [comment] 2020-11-17 16:22
> I can't find how to update a variation on the cart though.

The latest commit (8df5d40e0f1b922f95b8fd1113500dd459d021c7) should fix this.

**Comment by alexpi** [comment] 2020-11-18 08:38
Sorry, I don't understand how to use updateItem to update a variation. I have the following code:
```php
'pattern' => 'shop-api/update-cart-item',
'method' => 'POST',
'action' => function() {
  try {
    $data = kirby()->request()->data();
    $product = kirby()->page($data['id']);

    $cart = merx()->cart();

    $cart->updateItem([
      'id' => $data['variation'],
      'quantity' => (float) ($data['quantity'] ?? 1),
    ]);

    $item = [
      'id' => $data['id'],
      'variation' => $data['variation'],
      'buildtime' => ((float) $data['quantity'] === 1) ? 'false' : buildtime($product, $data['material'], $data['variations']),
      'total' => $cart->find($data['variation'])['sum']
    ];
  
    return [
      'status' => 200,
      'item' => $item,
      'cart' => [
        'total' => $cart->getSum(),
        'count' => $cart->count()
      ]
    ];
  } catch (Kirby\Exception\Exception $ex) {
    return $ex->toArray();
  }
}    
```
When calling ```updateItem```, I am passing the ```variation``` in order to find it in the cart, but this action also changes the product's ```id```, which I need in order to get the original product page.

**Comment by tobiasfabian** [comment] 2020-11-18 09:23
Sorry I forgot to explain the changes of the commit.

If you are working with product variants you have to use `key` instead of `id` to update the cart item.

This is how it should work. 

```php
    $cart->updateItem([
      'key' => $data['variation'],
      'quantity' => (float) ($data['quantity'] ?? 1),
    ]);
```

**Closed** 2021-01-05 22:27 UTC
